server:
  port: 80
  error:
    path: /error
spring:
  jpa:
    generate-ddl: true
#    hibernate:
#      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/practice
    username: postgres
    password: root